### ISSUE TITLE
px68k-libretro core altering roms and corrupting .zip files

### ISSUE THREAD

**Issue by huoshankonglong** [libretro/px68k-libretro#136]
Hello,

The Px68k core is altering every .dim and .zip file I load up.
.dim and .zip files change size and the .zip files become corrupted.
The .dim files I've tried permanently change from 1,233 KB to 1,361 KB.

(Tested on two installs of x86_64 Retroarch ver. 1.9.0, with px68k_libretro.dll core downloaded through Retroarch as of 3-12-2021)

Thank you

**Comment by negativeExponent** [comment]
- altering rom/disk images directly is what this core does, and that is normal. If you dont want you rom to change/updated due to disk writes, then if its just a single-rom game, then just compress it, and use the zip to play, other wise if you load a game which is in unzipped form, it will directly write to them.

 - altering and changing .zip files could not be possible unless caused by some certain other issues. Normally, when loading compressed images (.zip), the file will be extracted to the same folder and then loaded into core. regardless if this rom has been changed or not,  the rom will be discarded once you close the content. Retroarch/the core itself will not alter the zip file in any way (i've not heard of such happening).

**Comment by negativeExponent** [comment]
zip handling should not be possible in the core. it was wrongly configure to open zip directly. pushed a PR to prevent this core from opening and possible changing zip files.

with regards to files changing size, its practically normal, for this core at least. Some of these filetypes were oversized to begin with, so when it gets loaded to the core, its file manager changes it to have the correct size/headers. Since the core writes directly to the image file, then your source files will change as well. Unless it was not stated in the docs.libretro.com, it was adviced to keep a copy of your unchanged source files and play from a backup/separate copy instead.

**Comment by negativeExponent** [comment]
this should already be fixed
