### ISSUE TITLE
Core Crashes Loading Content on Self Compiled RetroArch

### ISSUE THREAD

**Issue by Awakened0** [libretro/px68k-libretro#147]
I can load content fine with Win64 buildbot builds of RetroArch. But with a build compiled with msys2 myself, it crashes when loading content. I can start the core in my build, but if I try to exit the menu with F12 or L2 it crashes. This is the crash log I got:

https://pastebin.com/51B9kLeP

**Comment by Awakened0** [comment]
I got around to building the core with the extra linker flags. While it does work with official RetroArch nightlies from the buildbot, it still crashes with my [Minimal builds](https://github.com/Awakened0/RetroArch-Minimal-Builds/releases/tag/Main) made with msys2 in Github Actions. Maybe ASLR has to be disabled when building RetroArch as well?

**Comment by gouchi** [comment]
Hi,

The core should be available on buildbot now, otherwise you can get the build directly for [i686](https://git.libretro.com/libretro/px68k-libretro/-/jobs/2367013/artifacts/download) or [x86_64](https://git.libretro.com/libretro/px68k-libretro/-/jobs/2367012/artifacts/download).

If the issue is fixed after testing please close it.

Thank you.

**Comment by Awakened0** [comment]
Yep, tested the latest buildbot build with my minimal RA build and no crashing!
