### ISSUE TITLE
Code Zero stuck on boot

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/px68k-libretro#30]
This game stays on a black screen after the Enix logo.
Works fine in winx68k & px68k android. It's a 61.46Hz game.

It spams this in the background:
KeyBufRP:1, KeyBufWP:2

https://github.com/libretro/px68k-libretro/blob/master/libretro/keyboard.c#L633
Annotation is: 
"Key check. It's called 4 times （if 2400bps/10bit/60fps） per frame, data is sent to the MFP."

[The MFP.](https://github.com/libretro/px68k-libretro/blob/master/x68k/mfp.c)

edit: well, probably just a key repeat because it's stuck and I pushed something.

**Comment by retro-wertz** [comment]
@r-type Hi, found out what is causing the issue. the cpu is generating an opcode 0x9809 which is designated as one of many opcodes with  CPU_FAULTED condition which causes the emulator to stop processesing(you can still go into the menu with F12).
https://github.com/libretro/px68k-libretro/blob/master/m68000/c68k/c68k_op9.inc#L151

comparing to hisorri's fork and the original keropi asm-based. these opcodes  addressed as CPU_FAULTED condition are not declared or even used. 

commenting this line should fix Code Zero issue:
https://github.com/libretro/px68k-libretro/blob/master/m68000/c68k/c68k_op9.inc#L91
"to //case 0x9809:" to skip this opcode
since for now that is the opcode generated that stops Code Zero after logo screen. not sure if there will be other faulted opcodes ingame or in some other games though.

reference opcode lists :  
hisorii's fork, c68k_op.c
win68k-asm src - comptab.asm

**Comment by r-type** [comment]
You are right , trying just to return  here instead of dealing error . and it works fine.

// SUBaD
case 0x9008:
{
	u32 res;
	pointer dst;
	pointer src;
RET(4)
	// can't read byte from Ax registers !
	CPU->Status |= C68K_FAULTED;
	CCnt = 0;
	goto C68k_Exec_Really_End;
	dst = (u8)CPU->D[(Opcode >> 9) & 7];
	res = (u32)(dst - src);
	CPU->flag_N = CPU->flag_X = CPU->flag_C = res;
	CPU->flag_V = ((u32)src ^ (u32)dst) & (res ^ (u32)dst);
	CPU->flag_notZ = res & 0xFF;
	*(BYTE_OFF + (u8*)(&CPU->D[(Opcode >> 9) & 7])) = res;
}
RET(4)

**Comment by retro-wertz** [comment]
actually you probably not need to move RET(4) there as those deduct cycles. there is already a call to "**C68k_Exec_Really_End**" a few lines down but having **CPU->Status |= C68K_FAULTED** before calling **goto** halts emulation. what the old cpu core did was to totally ignore this Opcode(and cpu condition) and others relatiNG to  **C68K_FAULTED**.

you can just probably do a **break:** there instead before doing any instructions or just use there **goto C68k_Exec_End**  since this is the next instruction assuming opcode 0x9008 is ignored.

**Comment by retro-wertz** [comment]
PR should be commited for this. If anyone can playthrough the game to find any more hang-up-causing opcodes the better, else this should be working now.

**Comment by Tatsuya79** [comment]
This was fixed.
