### ISSUE TITLE
FDD blocking HDF from loading

### ISSUE THREAD

**Issue by telanus** [libretro/px68k-libretro#38]
hi

If one load a FDD based game, and exit then load a HDF based game the previously loaded FDD based game will run and not the HDF one. IE if I load Metal Orange EX (FDD based) and then try and load Can Can Bunny Extra (HDF based) RA will load Metal Orange EX and not Can Can Bunny Extra. 

There must be an easier way as the only way I've found to get around this annoyance is to manually edit the config file by hand each time you run a px68k based game

**Comment by r-type** [comment]
you can get into menu , remove the floppy from here and reset emulator.

**Comment by gingerbeardman** [comment]
Yes you need to eject  the floppy.

**Comment by zerojay** [comment]
While yes, you can do that, you shouldn't need to. Especially as no other libretro emulator core based on PCs does this. They all start up with empty floppy drives by default unless the user specifies a floppy to load on a command line.

**Comment by gingerbeardman** [comment]
I've changed this, watch out for it soon

**Comment by Exalm** [comment]
Does PX68k even need to write the `keropi/config` file? Things like `WinPosX` etc don't even make sense for libretro...

**Comment by gingerbeardman** [comment]
I'm yet to push my changes. Will do very soon

**Comment by Exalm** [comment]
Yeah, 2 months is very "soon" ;)

**Comment by gingerbeardman** [comment]
That's life 🌍

**Comment by Exalm** [comment]
Sorry, I don't buy it. This is a work for about a minute, as the linked pull request shows.

**Comment by gingerbeardman** [comment]
Sure, it does. I shouldn't take you much longer to compile it yourself. 

My changes encompass so much more than just the change you're hung up on.

**Comment by Exalm** [comment]
Why should that even be an option? None of the other cores do that.
I'd personally just remove the keropi/config and related code completely (about half of those options are unused right now) and move the remaining stuff to core options. If people are ok with that, I'm happy to just do that.

**Comment by gingerbeardman** [comment]
You seem pretty worked up about this? There's no need to be I can assure you. 😄 

In my option "persist HDD" should be an option, defaulting to the existing behaviour, because it's changing the long-standing behaviour of the emulator. 

Those people who mainly use floppies, and who would rather not have the HDDs persist can then set the option, and everybody else will be non-the-wiser. FYI I use HDDs so them persisting is just like a hard drive plugged into a computer - they are always there.

### Here's what I've done so far:
* menu translated into English
  - clarified some settings options
  - increased size of options window
  - language option
* better file list
  - increased size of file list window
  - sorted alphabetically, folders first followed by files (@ptitSeb)
  - left/right to jump 8 items at a time (@ptitSeb)
  - hold R2 for high speed browsing (@ptitSeb, @gingerbeardman)
  - directory traversal now remembers history
  - contrasting colours for directories and files
  - files starting with . or $ are now hidden
  - increased maximum number of files shown per folder
* option for disks to not persist between launches
* auto frame skip now default (@ptitSeb)
* fixed some small bugs (@ptitSeb)

### To do:
* MouseKey
* improved key repeat

### Screenshot:
![screen shot 2018-04-14 at 17 26 01](https://user-images.githubusercontent.com/49612/38770318-0a191d5a-4009-11e8-9d2d-a1ed01327c8c.png)

**Comment by Darknior** [comment]
WOOAAAWWW !!! to rad all you make for this emulator <3
I love the x68000 and have a fantastic best of set that come from my old xBox where we can play x68000 perfectly from some years.
Now i'm on PI3 and i really want to port my pack to it :)
This libretro is really a chance for us ... 

- With your future change and US menu, do you think it will be possible to play all the x68000 games ?
It can really be a dream :)
http://www.theisozone.com/downloads/xbox/emulators/sharp-x68000-emuxtras/
http://www.emuxtras.net/forum/viewtopic.php?f=64&t=2226&start=90

- I understand you update the menu of the emulator and not the Libretro CORE options because the LR menu is really small and not really upgradable. It's the problem for all the computers like AMIGA and others ...
BUT, do you think it will be possible to link some of them to LR engine to use this emulator like others, like the SNES for exemple. To let us using SAVESTATE with HOTKEY, REWIND, FAST FORWARD, etc ...
And like on AMIGA with UEA files let us creating config file for each games if there is something special with it?

Thanks a lot

**Comment by gingerbeardman** [comment]
@Darknior now that the discussion is branching to things not really related to the original issue, let's do to things:

- create one issue for each of your ideas on github
https://github.com/libretro/px68k-libretro/issues/new
  1. X68000 database (box art, notes, config, cheats)
  2. Add PX68K options to RA core options menu
  3. Support for save states
  4. Support for rewind
  5. Support for fast forward
  6. Support for saving game overrides, or one keropi/config per game
  7. Add French localisation to PX68K menu items
- let's take further general discussion over to the libretro forums
https://forums.libretro.com/t/px68k-libretro/10113/203

**Comment by Darknior** [comment]
Have you comit these change ?
I don't have them on my x68000 emu with Batocera and i don't understand how to eject the floppy disk.
Thanks

**Comment by negativeExponent** [comment]
you can actually run core without content, that should at least remedy the auto loading and launching of fdd/hdd

**Comment by Darknior** [comment]
Thanks for your answer @negativeExponent .
But no really, because on Batocera or Retropie or Recallbox we use the EmulationStation menu and it launch the game we choose. We can't choose nothing. And it's a bad trick to ask users to launch nothing to launch a game :(
I really not understand why you do it by default ?
If i understand fine this new update menu has nerver been comit :(

I have finally launch an HDF game and it is really really really slow :(
Not understand why, all other DIM games are working fine full speed.

**Comment by negativeExponent** [comment]
you can have quick menu though on those launchers right? if so it be a quick core options addition.

what game is slow? might be the game is using high resolution mode (text-mode based game or something to have higher resolutions)

**Comment by Darknior** [comment]
> you can have quick menu though on those launchers right? if so it be a quick core options addition.

Yes maybe i can ask for it, but it is crappy ;(
The gamers play with a pad, my children want to play fast. The x68000 is some time slow to load a game, if they must also use F12 not on the pad with keyboard to search a menu to search a game file in 400 files, to choose it and launch it !!!!
No one will never do it for sure :(
Really we must found a better solution for the "main public". Or the x68000 will stay a curiosity computer that no one using :(

An other solution maybe if you can't modify the core was to use a .SH script to remove the game from the ini file ?
Where is this ini file ? Can we delete it ?

**Comment by Darknior** [comment]
@gingerbeardman. sorry to boring you, what do you think about my script bash solution ?
Batocera met us launching a script .sh before and after a game. It is not the best way but it can do the trick for the moment.
If i can delete the INI file or maybe the line in the INI file to launch an hard drive game without any floppy disc.
Always to make it easy for children and common users ....
Thanks a lot

**Comment by negativeExponent** [comment]
i may have seen something that may have cause slow access on networked drives (other than the slow network itself). but the fix will require to cache the image files into memory, which will in turn make the core use more memory. its not a problem on PC, but may be an issue memory-constraint portable devices. this appears to happend on HDD based images. px68l only keeps a portion of data, and will constantly read to-or.from the image file when it needs to.

**Comment by negativeExponent** [comment]
you can either eject FDD from menu, or disable fdd path saving from core options. this should remedy this problem.

otherwise, assume this resolved.
