### ISSUE TITLE
[Enhancement] Add French localisation to PX68K menu items

### ISSUE THREAD

**Issue by Darknior** [libretro/px68k-libretro#63]
Hi
For this request i can help like i already do on other projects.
If you give me a file with all the TEXT to translate i can do it for you.
Thanks

**Comment by gingerbeardman** [comment]
Yes, I'll do this after I commit my current changes

**Comment by retro-wertz** [comment]
ive translated menu items to english. you can refer to it and submit translation for the text and maybe we can add a core option to select which language to use for the menu.

**Comment by negativeExponent** [comment]
@Darknior you can start helping by translating these to Fresh so we can add the language and change the core options:

https://github.com/libretro/px68k-libretro/blob/master/libretro_core_options.h#L57

example lines to translate

```
{
      "px68k_cpuspeed",
      "CPU Speed",
      "Configure the CPU speed. Can be used to slow down games that run too fast or to speed up floppy loading times.",
      {
         { "10Mhz",       NULL },
         { "16Mhz",       NULL },
         { "25Mhz",       NULL },
         { "33Mhz (OC)",  NULL },
         { "66Mhz (OC)",  NULL },
         { "100Mhz (OC)", NULL },
         { "150Mhz (OC)", NULL },
         { "200Mhz (OC)", NULL },
         { NULL,          NULL },
      },
      "10Mhz"
   },
```
 **"CPU Speed"**, <= this needs to be translated since this is the main core option label.
The next line is a short description of the option. Probably this needs translating also. 

Send the translated text to me and i can add this to alternate languages

**Comment by Darknior** [comment]
Done ;)
https://github.com/libretro/px68k-libretro/pull/117

**Comment by negativeExponent** [comment]
> Done ;)
> #117

thanks see notes. i added some corrections needed

**Comment by Darknior** [comment]
With pleasure :)

**Comment by negativeExponent** [comment]
i assume that this should working by now. 

closing.
